### ISSUE TITLE
Change configuration to be configurable in slash command

### ISSUE THREAD

**Issue by spirosoik** [mattermost/mattermost-app-chaosengine#9]
Right now we have a configuration to setup a database connection [here](https://github.com/mattermost/mattermost-app-chaosengine/blob/master/config/config.go#L35) and we use [Viper](https://github.com/spf13/viper) for getting the configuration through environment variables.

This works for the HTTP type of a Mattermost App Framework well and for self-managed but for Cloud where the App is deployed is not possible to have some kind of configuration. So we want to have the ability to do it with `/chaos-engine configure` which will have the details for the DB connection string and the whole app will use this to connect to DB.

A similar example can be found in `ServiceNow app` [here](https://github.com/mattermost/mattermost-app-servicenow/blob/master/routers/mattermost/fConfigureOAuth.go)

**Comment by hydeenoble** [comment]
@spirosoik I would like to start with this, can you please assign it to me?

**Comment by spirosoik** [comment]
@hydeenoble go for it

**Comment by hydeenoble** [comment]
Thanks!

**Comment by hydeenoble** [comment]
> @hydeenoble go for it

Thanks!
